name: auth
description: Firebase authentification.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_facebook_auth: ^3.3.3+1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.0.2
  provider: ^5.0.0

dev_dependencies:
  dart_code_metrics: ^3.2.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
